package main

// wasmMaterials maps material index to name, matching wasm/materials.ts.
var wasmMaterials = []string{
	"acid",
	"alcohol",
	"blood",
	"blood_fungi",
	"blood_worm",
	"cement",
	"lava",
	"magic_liquid_berserk",
	"magic_liquid_charm",
	"magic_liquid_faster_levitation",
	"magic_liquid_faster_levitation_and_movement",
	"magic_liquid_invisibility",
	"magic_liquid_mana_regeneration",
	"magic_liquid_movement_faster",
	"magic_liquid_protection_all",
	"magic_liquid_teleportation",
	"magic_liquid_unstable_polymorph",
	"magic_liquid_unstable_teleportation",
	"magic_liquid_worm_attractor",
	"material_confusion",
	"mud",
	"oil",
	"poison",
	"radioactive_liquid",
	"swamp",
	"urine",
	"water",
	"water_ice",
	"water_swamp",
	"magic_liquid_random_polymorph",
	"bone",
	"brass",
	"coal",
	"copper",
	"diamond",
	"fungi",
	"gold",
	"grass",
	"gunpowder",
	"gunpowder_explosive",
	"rotten_meat",
	"sand",
	"silver",
	"slime",
	"snow",
	"soil",
	"wax",
	"honey",
	"water_static",
	"water_salt",
	"material_darkness",
	"peat",
	"fungisoil",
	"blood_cold",
	"acid_gas",
	"acid_gas_static",
	"poison_gas",
	"fungal_gas",
	"radioactive_gas",
	"radioactive_gas_static",
	"magic_liquid_polymorph",
	"steam",
	"smoke",
	"snow_sticky",
	"rock_static",
	"gold_box2d",
	"sima",
	"vomit",
	"pea_soup",
	"rock_static_radioactive",
	"mimic_liquid",
	"poo",
	"void_liquid",
	"cheese_static",
	"grass_holy",
	"mammi",
	"rotten_meat_radioactive",
}

func materialName(id int) string {
	if id < 0 || id >= len(wasmMaterials) {
		return ""
	}
	return wasmMaterials[id]
}
